In [2]:
import pandas as pd
data = {
    'name': ['Kim', 'Lee', 'Park'],
    'age': [25, 30, 35],
    'city': ['Seoul', 'Busan', 'Incheon']
}
df = pd.DataFrame(data)
df

   name  age     city
0   Kim   25    Seoul
1   Lee   30    Busan
2  Park   35  Incheon

In [4]:
data = [
    {'name': 'Kim', 'age': 25, 'city': 'Seoul'},
    {'name': 'Lee', 'age': 30, 'city': 'Busan'},
    {'name': 'Park', 'age': 35, 'city': 'Incheon'}
]
df = pd.DataFrame(data)
df

   name  age     city
0   Kim   25    Seoul
1   Lee   30    Busan
2  Park   35  Incheon

In [6]:
data = [
    ['Kim', 25, 'Seoul'],
    ['Lee', 30, 'Busan'],
    ['Park', 35, 'Incheon']
]
df = pd.DataFrame(data, 
                   columns=['name', 'age', 'city']
                  )
df

   name  age     city
0   Kim   25    Seoul
1   Lee   30    Busan
2  Park   35  Incheon

In [14]:
s1 = pd.Series(['Kim', 'Lee', 'Park'])
s2 = pd.Series([25, 30, 35],index=['a','b','c'])
df = pd.DataFrame({'name': s1, 'age': s2})
df

   name   age
0   Kim   NaN
1   Lee   NaN
2  Park   NaN
a   NaN  25.0
b   NaN  30.0
c   NaN  35.0

In [22]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])
c = pd.Series([7, 8, 9])

pd.DataFrame( {'a':a,'b':b,'c':c} )
pd.DataFrame( (a,b,c) )

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [28]:
# df.shape        # (행 수, 열 수)
# df.size         # 전체 요소 개수
# df.ndim         # 차원 (항상 2)
# df.index        # 인덱스 객체
# df.columns      # 컬럼 객체
# df.values       # NumPy 배열
# df.dtypes       # 각 컬럼의 데이터 타입
data = {
    'city' : ['서울','대전','대구','부산'],
    'data1' : np.random.randint(100000,1000000,4),
    'data2' : np.random.randn(4),
}
df = pd.DataFrame(data)
df
print(df.shape)  # ( 4 , 3 )
print(df.size) # 12
print(df.ndim)
print(list(df.index))
print(df.columns)
print(df.values)
print(df.dtypes)

(4, 3)
12
2
[0, 1, 2, 3]
Index(['city', 'data1', 'data2'], dtype='object')
[['서울' 346889 -1.0902156562814151]
 ['대전' 382293 -0.5926334755044298]
 ['대구' 695515 0.7218071980446313]
 ['부산' 904395 -1.829041868319447]]
city      object
data1      int32
data2    float64
dtype: object

In [ ]:
df.info()  # 전체 정보 (타입, 결측치 등)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   city    4 non-null      object
 1   data1   4 non-null      int32
 2   data2   4 non-null      float64
dtypes: float64(1), int32(1), object(1)
memory usage: 212.0+ bytes

In [37]:
df.describe(include='object')

       city
count     4
unique    4
top      서울
freq      1

In [38]:
data = {
    'city' : ['서울','대전','대구','부산'],
    'data1' : np.random.randint(100000,1000000,4),
    'data2' : np.random.randn(4),
}
df = pd.DataFrame(data)
df

  city   data1     data2
0   서울  891773 -0.343986
1   대전  103569 -0.252838
2   대구  772088  0.210509
3   부산  447605 -0.739663

In [57]:
df['salary'] = [3000, 4000, 5000,6000]
df['salary2'] = 0
df2 = df.copy()
df2

  city   data1     data2  salary  salary2
0   서울  891773 -0.343986    3000        0
1   대전  103569 -0.252838    4000        0
2   대구  772088  0.210509    5000        0
3   부산  447605 -0.739663    6000        0

In [ ]:
df2.drop('salary2',axis=1)

  city   data1     data2  salary
0   서울  891773 -0.343986    3000
1   대전  103569 -0.252838    4000
2   대구  772088  0.210509    5000
3   부산  447605 -0.739663    6000

In [ ]:
df2.columns = ['city', 'data10', 'data20', 'salary', 'salary2']

  city  data10    data20  salary  salary2
0   서울  891773 -0.343986    3000        0
1   대전  103569 -0.252838    4000        0
2   대구  772088  0.210509    5000        0
3   부산  447605 -0.739663    6000        0

In [95]:
filepath = '20250731.csv'
df = pd.read_csv(filepath)
df.head()
# 결측치 개수
for colname in df:
    print(colname, df[df[colname].isna()].shape[0])

# 기술통계(숫자컬럼만)  기술통계(문자들만)
print(df.describe(include='object'))

# info() 사용해 보기
# 소속 시장명(또는 상점가) 의 컬럼명을 시장명-상점가  로 변경
# 소재지 그리고 취급품목들 등록년도의 각각의 개수
# 소재지 그리고 취급품목들 등록년도의 각각의 종류들
print(df['소재지'].unique())
# 지류형 가맹 여부 가 N인 데이터로 이루어진 데이터프레임 즉 데이터 출력
print(df[df['지류형 가맹 여부'] == 'N'])
# 등록년도 컬럼 삭제하기
df.drop('등록년도',axis=1)
# 등록년도 컬럼 삭제해서 원본을 변경하기
# df = df.drop('등록년도',axis=1)
df.drop('등록년도',axis=1,inplace=True)
df

가맹점명 40
소속 시장명(또는 상점가) 0
소재지 0
취급품목 293
지류형 가맹 여부 0
디지털형 가맹 여부 0
등록년도 0
          가맹점명 소속 시장명(또는 상점가)     소재지    취급품목 지류형 가맹 여부 디지털형 가맹 여부
count   150501         150541  150541  150248    150541     150541
unique  115898           2651      17   22115         1          2
top         노점          남대문시장      서울      한식         Y          Y
freq      2093            846   24190   11604    150541     134338
['경기' '광주' '충남' '전북' '충북' '전남' '서울' '제주' '경남' '대전' '인천' '부산' '강원' '울산'
 '세종' '대구' '경북']
Empty DataFrame
Columns: [가맹점명, 소속 시장명(또는 상점가), 소재지, 취급품목, 지류형 가맹 여부, 디지털형 가맹 여부, 등록년도]
Index: []

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y
...,...,...,...,...,...,...
150536,태성마트,단양구경시장(단양인정시장),충북,식잡,Y,Y
150537,동산닭집,단양구경시장(단양인정시장),충북,"일반한식,생닭",Y,Y
150538,파마미용실,단양구경시장(단양인정시장),충북,일반미용업,Y,Y
150539,두메하누,단양구경시장(단양인정시장),충북,한식점업,Y,Y
150540,단양보리밥,단양구경시장(단양인정시장),충북,분식,Y,Y

In [97]:
filepath = '20250731.csv'
df = pd.read_csv(filepath)
df2 = df.head().copy()
df2

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025

In [99]:
df3 = df2.set_index('소재지').copy()
df3

,가맹점명,소속 시장명(또는 상점가),취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
소재지,,,,,,
경기,초마맨1981,권율 골목형상점가,짜장면 짬뽕 탕수육,Y,Y,2025
광주,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",꽈배기 도너츠,Y,Y,2025
광주,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",열쇠,Y,Y,2025
경기,참새 방앗간,권율 골목형상점가,육전 새우전,Y,Y,2025
광주,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",미용,Y,Y,2025

In [115]:
# df3.loc['광주','가맹점명':'취급품목']
df3.iloc[[1,2,4], 0:3]

        가맹점명                소속 시장명(또는 상점가)     취급품목
소재지
광주   못난이 꽈배기  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)  꽈배기 도너츠
광주    일곡열쇠철물  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)       열쇠
광주     뿔라헤어컷  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)       미용

In [131]:
sample_df1 = df.iloc[:5,:2]
sample_df2 = df.iloc[-5:,:2]
sample_df1

      가맹점명                소속 시장명(또는 상점가)
0  초마맨1981                     권율 골목형상점가
1  못난이 꽈배기  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
2   일곡열쇠철물  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
3   참새 방앗간                     권율 골목형상점가
4    뿔라헤어컷  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)

In [132]:
sample_df2

         가맹점명  소속 시장명(또는 상점가)
150536   태성마트  단양구경시장(단양인정시장)
150537   동산닭집  단양구경시장(단양인정시장)
150538  파마미용실  단양구경시장(단양인정시장)
150539   두메하누  단양구경시장(단양인정시장)
150540  단양보리밥  단양구경시장(단양인정시장)

In [134]:
sample_df3 = pd.concat([sample_df1,sample_df2],axis=0)
sample_df3

           가맹점명                소속 시장명(또는 상점가)
0       초마맨1981                     권율 골목형상점가
1       못난이 꽈배기  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
2        일곡열쇠철물  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
3        참새 방앗간                     권율 골목형상점가
4         뿔라헤어컷  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
150536     태성마트                단양구경시장(단양인정시장)
150537     동산닭집                단양구경시장(단양인정시장)
150538    파마미용실                단양구경시장(단양인정시장)
150539     두메하누                단양구경시장(단양인정시장)
150540    단양보리밥                단양구경시장(단양인정시장)

In [135]:
sample_df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 150540
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   가맹점명            10 non-null     object
 1   소속 시장명(또는 상점가)  10 non-null     object
dtypes: object(2)
memory usage: 240.0+ bytes

In [145]:
sample_df4 = sample_df3.reset_index()
sample_df4.rename(columns={'index':'data'},inplace=True)
sample_df4.set_index('가맹점명').reset_index()

      가맹점명    data                소속 시장명(또는 상점가)
0  초마맨1981       0                     권율 골목형상점가
1  못난이 꽈배기       1  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
2   일곡열쇠철물       2  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
3   참새 방앗간       3                     권율 골목형상점가
4    뿔라헤어컷       4  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
5     태성마트  150536                단양구경시장(단양인정시장)
6     동산닭집  150537                단양구경시장(단양인정시장)
7    파마미용실  150538                단양구경시장(단양인정시장)
8     두메하누  150539                단양구경시장(단양인정시장)
9    단양보리밥  150540                단양구경시장(단양인정시장)

In [ ]:
sample_df3.reset_index()
sample_df3.reset_index(drop=True)

      가맹점명                소속 시장명(또는 상점가)
0  초마맨1981                     권율 골목형상점가
1  못난이 꽈배기  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
2   일곡열쇠철물  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
3   참새 방앗간                     권율 골목형상점가
4    뿔라헤어컷  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)
5     태성마트                단양구경시장(단양인정시장)
6     동산닭집                단양구경시장(단양인정시장)
7    파마미용실                단양구경시장(단양인정시장)
8     두메하누                단양구경시장(단양인정시장)
9    단양보리밥                단양구경시장(단양인정시장)

In [149]:
import pandas as pd
filepath = '20250731.csv'
df = pd.read_csv(filepath)
df.head()

,가맹점명,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025

In [169]:
# 2020년 이후 데이터만 추출
df[df['등록년도'].isin( [2020, 2025])]['등록년도'].unique()

array([2025, 2020])