In [2]:
import pandas as pd
data = {
    'name': ['Kim', 'Lee', 'Park'],
    'age': [25, 30, 35],
    'city': ['Seoul', 'Busan', 'Incheon']
}
df = pd.DataFrame(data)
df

   name  age     city
0   Kim   25    Seoul
1   Lee   30    Busan
2  Park   35  Incheon

In [4]:
data = [
    {'name': 'Kim', 'age': 25, 'city': 'Seoul'},
    {'name': 'Lee', 'age': 30, 'city': 'Busan'},
    {'name': 'Park', 'age': 35, 'city': 'Incheon'}
]
df = pd.DataFrame(data)
df

   name  age     city
0   Kim   25    Seoul
1   Lee   30    Busan
2  Park   35  Incheon

In [6]:
data = [
    ['Kim', 25, 'Seoul'],
    ['Lee', 30, 'Busan'],
    ['Park', 35, 'Incheon']
]
df = pd.DataFrame(data, 
                   columns=['name', 'age', 'city']
                  )
df

   name  age     city
0   Kim   25    Seoul
1   Lee   30    Busan
2  Park   35  Incheon

In [14]:
s1 = pd.Series(['Kim', 'Lee', 'Park'])
s2 = pd.Series([25, 30, 35],index=['a','b','c'])
df = pd.DataFrame({'name': s1, 'age': s2})
df

   name   age
0   Kim   NaN
1   Lee   NaN
2  Park   NaN
a   NaN  25.0
b   NaN  30.0
c   NaN  35.0

In [22]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])
c = pd.Series([7, 8, 9])

pd.DataFrame( {'a':a,'b':b,'c':c} )
pd.DataFrame( (a,b,c) )

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [28]:
# df.shape        # (행 수, 열 수)
# df.size         # 전체 요소 개수
# df.ndim         # 차원 (항상 2)
# df.index        # 인덱스 객체
# df.columns      # 컬럼 객체
# df.values       # NumPy 배열
# df.dtypes       # 각 컬럼의 데이터 타입
data = {
    'city' : ['서울','대전','대구','부산'],
    'data1' : np.random.randint(100000,1000000,4),
    'data2' : np.random.randn(4),
}
df = pd.DataFrame(data)
df
print(df.shape)  # ( 4 , 3 )
print(df.size) # 12
print(df.ndim)
print(list(df.index))
print(df.columns)
print(df.values)
print(df.dtypes)

(4, 3)
12
2
[0, 1, 2, 3]
Index(['city', 'data1', 'data2'], dtype='object')
[['서울' 346889 -1.0902156562814151]
 ['대전' 382293 -0.5926334755044298]
 ['대구' 695515 0.7218071980446313]
 ['부산' 904395 -1.829041868319447]]
city      object
data1      int32
data2    float64
dtype: object

In [ ]:
df.info()  # 전체 정보 (타입, 결측치 등)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   city    4 non-null      object
 1   data1   4 non-null      int32
 2   data2   4 non-null      float64
dtypes: float64(1), int32(1), object(1)
memory usage: 212.0+ bytes

In [37]:
df.describe(include='object')

       city
count     4
unique    4
top      서울
freq      1

In [38]:
data = {
    'city' : ['서울','대전','대구','부산'],
    'data1' : np.random.randint(100000,1000000,4),
    'data2' : np.random.randn(4),
}
df = pd.DataFrame(data)
df

  city   data1     data2
0   서울  891773 -0.343986
1   대전  103569 -0.252838
2   대구  772088  0.210509
3   부산  447605 -0.739663

In [57]:
df['salary'] = [3000, 4000, 5000,6000]
df['salary2'] = 0
df2 = df.copy()
df2

  city   data1     data2  salary  salary2
0   서울  891773 -0.343986    3000        0
1   대전  103569 -0.252838    4000        0
2   대구  772088  0.210509    5000        0
3   부산  447605 -0.739663    6000        0

In [ ]:
df2.drop('salary2',axis=1)

  city   data1     data2  salary
0   서울  891773 -0.343986    3000
1   대전  103569 -0.252838    4000
2   대구  772088  0.210509    5000
3   부산  447605 -0.739663    6000

In [ ]:
df2.columns = ['city', 'data10', 'data20', 'salary', 'salary2']
df2``

  city  data10    data20  salary  salary2
0   서울  891773 -0.343986    3000        0
1   대전  103569 -0.252838    4000        0
2   대구  772088  0.210509    5000        0
3   부산  447605 -0.739663    6000        0